import pandas as pd
ROOT = r"C:\Users\alexandre bandarra\Desktop\global"
m = pd.read_csv(rf"{ROOT}\data\v4\refresh_2026_05_06\markets_full.csv")
print("cols:", list(m.columns))
print("shape:", m.shape)
print("ticker counts:", m.ticker.value_counts().to_dict())
print("timeframe counts:", m.timeframe.value_counts().to_dict())
print("status counts:", m.status.value_counts().to_dict())
m['ws'] = m.slug.str.extract(r'-(\d+)$')[0].astype('Int64')
print("ws null:", m.ws.isna().sum(), "min/max:", int(m.ws.min()), int(m.ws.max()))
print()
r = pd.read_csv(rf"{ROOT}\data\v4\refresh_2026_05_06\market_resolutions_full.csv")
print("resolutions cols:", list(r.columns))
print("resolutions shape:", r.shape)
print("res outcome counts:", r.outcome.value_counts().to_dict())
print("res unique slugs:", r.slug.nunique())
both = m.merge(r[['slug','outcome']].rename(columns={'outcome':'res_outcome'}), on='slug', how='left')
print("merged rows:", both.shape, "with resolution:", both.res_outcome.notna().sum())
mask = (both.outcome.notna()) & (both.res_outcome.notna())
print("disagreement (markets.outcome vs res_outcome):", ((mask) & (both.outcome != both.res_outcome)).sum())
print()
# Filter to BTC/ETH/SOL UpDown 5m/15m markets, resolved
sub = m[(m.ticker.isin(['BTC','ETH','SOL'])) & (m.timeframe.isin(['5m','15m']))].copy()
sub = sub.merge(r[['slug','outcome']].rename(columns={'outcome':'res_outcome'}), on='slug', how='left')
print("BTC/ETH/SOL × 5m/15m × resolved:", sub.dropna(subset=['res_outcome']).shape[0])
print("by (ticker, tf):")
print(sub.dropna(subset=['res_outcome']).groupby(['ticker','timeframe']).size().to_dict())
