"""Apply microstructure gates as OVERLAYS on top sleeves (TASK 3, deep version).

Top sleeves to test (from shadow_11_sleeves_v2 + hybrid universe):
  - poly_updown_btc_15m_momo_v2
  - poly_updown_btc_15m_sniper
  - poly_updown_eth_15m_momo_v2
  - poly_updown_btc_5m_momo
  - poly_updown_sol_5m_momo_v2

But — we don't have the original sleeve firing rules wired in directly.
Instead: load shadow_11_sleeves backtest details from production trading_events
or use ret_2m_at_ws + sleeve-like cutoffs directly on fire_universe.

Since the fire_universe was generated by hybrid_fire_universe.py (Cyclops + momo combinatorial),
we can identify "sleeves" via filters on ret_2m_at_ws, mag_ratio, vwap, fire_offset:
  - "momo_v2_anywhere":  ret_2m_at_ws >= 0.0005 AND mag_ratio >= 2.0
  - "momo_v2_strong":    ret_2m_at_ws >= 0.001  AND mag_ratio >= 3.0
  - "sniper":            fire_offset_s in [120,240,360,480]  AND ret_2m_at_ws >= 0.0
  - "fade":              ret_2m_at_ws between -0.0005 and 0.0005
  - "hod_only":          ret_2m_at_ws >= 0.0008

We apply each microstructure gate as overlay on each (sleeve, asset, tf) and report lift.
"""
from __future__ import annotations
import sys, os, time
from pathlib import Path
import numpy as np
import pandas as pd

ROOT = Path(r"C:\Users\alexandre bandarra/Desktop/global")
sys.path.insert(0, str(ROOT / "strategy_lab" / "microstructure_2026_05_26"))
from score_panel import add_pnl_cols, build_gates

OUT_DIR = ROOT / "data" / "v4" / "canonical" / "_results"
WORK = ROOT / "strategy_lab" / "microstructure_2026_05_26"


def load_full_panel():
    """Load full microstructure panel WITH ret_2m, mag_ratio etc."""
    parts = []
    for asset in ["BTC", "ETH", "SOL"]:
        p = WORK / f"micro_panel_{asset.lower()}.parquet"
        if p.exists():
            parts.append(pd.read_parquet(p))
    panel = pd.concat(parts, ignore_index=True)
    fr5 = pd.read_parquet(OUT_DIR / "hybrid_fire_universe_5m.parquet")
    fr15 = pd.read_parquet(OUT_DIR / "hybrid_fire_universe_15m.parquet")
    fires = pd.concat([fr5, fr15], ignore_index=True)
    m = panel.merge(
        fires[["asset","slug","tf","fire_us","fire_offset_s","outcome",
               "up_fill_ok","dn_fill_ok","up_vwap","up_shares","up_usd",
               "dn_vwap","dn_shares","dn_usd",
               "ret_2m_at_ws","mag_ratio","vwap_since_open_bps","prod_q90"]],
        on=["asset","slug","tf","fire_us","fire_offset_s","outcome"], how="left",
    )
    m = add_pnl_cols(m)
    return m


def define_sleeves(p):
    """Each sleeve defines: subset of fires + direction (UP/DOWN/BIDIRECT).

    Returns dict[sleeve_name] -> (mask, direction_col_or_function)
      direction_col: a Series with values "Up"/"Down" indicating bet side per fire
    """
    sleeves = {}

    # momo_v2: bet WITH ret_2m direction at threshold
    # momo_v2_anywhere: |ret_2m| >= 0.0005 AND mag_ratio >= 1.5
    m1 = (p.ret_2m_at_ws.abs() >= 0.0005) & (p.mag_ratio >= 1.5)
    dir1 = np.where(p.ret_2m_at_ws > 0, "Up", "Down")
    sleeves["momo_v2_anywhere"] = (m1, pd.Series(dir1, index=p.index))

    # momo_v2_strong
    m2 = (p.ret_2m_at_ws.abs() >= 0.001) & (p.mag_ratio >= 2.5)
    dir2 = np.where(p.ret_2m_at_ws > 0, "Up", "Down")
    sleeves["momo_v2_strong"] = (m2, pd.Series(dir2, index=p.index))

    # sniper-style: only mid-window offsets
    m3 = (p.fire_offset_s.isin([120, 240, 360, 480])) & (p.ret_2m_at_ws.abs() >= 0.0003)
    dir3 = np.where(p.ret_2m_at_ws > 0, "Up", "Down")
    sleeves["sniper_midwindow"] = (m3, pd.Series(dir3, index=p.index))

    # fade — small ret_2m, bet WITH (mean reversion off small noise)
    m4 = (p.ret_2m_at_ws.abs() < 0.0003)
    dir4 = np.where(p.ret_2m_at_ws > 0, "Down", "Up")  # FADE
    sleeves["fade_small"] = (m4, pd.Series(dir4, index=p.index))

    # extreme momo — high ret AND mag
    m5 = (p.ret_2m_at_ws.abs() >= 0.0015) & (p.mag_ratio >= 3.0)
    dir5 = np.where(p.ret_2m_at_ws > 0, "Up", "Down")
    sleeves["momo_extreme"] = (m5, pd.Series(dir5, index=p.index))

    return sleeves


def compute_sleeve_pnl(p, mask, direction):
    """For a sleeve mask + direction, compute aggregated stats."""
    sub = p[mask].copy()
    if len(sub) == 0:
        return None
    pnl = np.where(direction[mask] == "Up",
                   sub.pnl_up.values,
                   sub.pnl_dn.values)
    fill_ok = np.where(direction[mask] == "Up",
                       sub.up_fill_ok.values,
                       sub.dn_fill_ok.values)
    won = (direction[mask] == sub.outcome).values
    return sub.assign(_pnl=pnl, _fill_ok=fill_ok, _won=won, _dir=direction[mask].values)


def task3_deep(p):
    """Apply each microstructure gate to each sleeve. Report lift."""
    sleeves = define_sleeves(p)
    rows = []
    gates_up, gates_dn = build_gates(p)

    for sname, (smask, sdir) in sleeves.items():
        sleeve_df = compute_sleeve_pnl(p, smask, sdir)
        if sleeve_df is None or len(sleeve_df) < 60:
            continue
        sleeve_df = sleeve_df[sleeve_df._fill_ok]
        if len(sleeve_df) < 60:
            continue
        for asset in ["BTC","ETH","SOL","ALL"]:
            for tf in ["5m","15m","ALL"]:
                sub = sleeve_df
                if asset != "ALL":
                    sub = sub[sub.asset == asset]
                if tf != "ALL":
                    sub = sub[sub.tf == tf]
                if len(sub) < 50:
                    continue
                # baseline
                base_dpt = sub._pnl.mean()
                base_wr = sub._won.mean()
                base_sum = sub._pnl.sum()
                rows.append({
                    "sleeve": sname, "asset": asset, "tf": tf,
                    "gate": "NONE",
                    "n_base": len(sub), "wr_base": float(base_wr),
                    "dpt_base": float(base_dpt), "sum_pnl": float(base_sum),
                    "wr_lift_pp": 0.0, "dpt_lift": 0.0,
                })
                # iterate gates — gate is direction-aware so we need to select per-fire
                for gname in gates_up.keys():
                    # gate value per fire: depends on bet direction
                    gate_per_fire = np.where(
                        sub._dir == "Up",
                        gates_up[gname].reindex(sub.index, fill_value=False).values,
                        gates_dn[gname].reindex(sub.index, fill_value=False).values,
                    )
                    sub2 = sub[gate_per_fire]
                    if len(sub2) < 30:
                        continue
                    dpt = sub2._pnl.mean()
                    wr = sub2._won.mean()
                    rows.append({
                        "sleeve": sname, "asset": asset, "tf": tf,
                        "gate": gname,
                        "n_base": len(sub), "wr_base": float(base_wr),
                        "dpt_base": float(base_dpt), "sum_pnl": float(sub2._pnl.sum()),
                        "wr_lift_pp": float((wr - base_wr) * 100),
                        "dpt_lift": float(dpt - base_dpt),
                        "n_gate": len(sub2), "wr_gate": float(wr),
                        "dpt_gate": float(dpt),
                    })
    df = pd.DataFrame(rows)
    return df


def task5_walkforward(p, df_top, train_frac=0.75, n_boot=200):
    """Walk-forward for top combos. df_top has columns sleeve/asset/tf/gate."""
    sleeves = define_sleeves(p)
    gates_up, gates_dn = build_gates(p)
    rows = []
    t_min = p.fire_us.min()
    t_max = p.fire_us.max()
    train_end_us = int(t_min + (t_max - t_min) * train_frac)
    rng = np.random.RandomState(42)
    for _, row in df_top.iterrows():
        sname = row["sleeve"]
        asset = row["asset"]
        tf = row["tf"]
        gname = row["gate"]
        if sname not in sleeves:
            continue
        smask, sdir = sleeves[sname]
        sub = compute_sleeve_pnl(p, smask, sdir)
        if sub is None:
            continue
        sub = sub[sub._fill_ok]
        if asset != "ALL":
            sub = sub[sub.asset == asset]
        if tf != "ALL":
            sub = sub[sub.tf == tf]
        # gate
        if gname != "NONE":
            gate_per_fire = np.where(
                sub._dir == "Up",
                gates_up[gname].reindex(sub.index, fill_value=False).values,
                gates_dn[gname].reindex(sub.index, fill_value=False).values,
            )
            sub = sub[gate_per_fire]
        if len(sub) < 30:
            continue
        train = sub[sub.fire_us < train_end_us]
        test = sub[sub.fire_us >= train_end_us]
        if len(train) < 15 or len(test) < 10:
            continue
        # Bootstrap test
        tps = test._pnl.values
        boot = np.array([rng.choice(tps, size=len(tps), replace=True).mean()
                         for _ in range(n_boot)])
        p_neg = float((boot < 0).mean())
        # Also bootstrap CI
        boot_low = float(np.percentile(boot, 5))
        boot_high = float(np.percentile(boot, 95))
        rows.append({
            "sleeve": sname, "asset": asset, "tf": tf, "gate": gname,
            "n_train": len(train), "wr_train": train._won.mean(),
            "dpt_train": train._pnl.mean(), "sum_train": train._pnl.sum(),
            "n_test": len(test), "wr_test": test._won.mean(),
            "dpt_test": test._pnl.mean(), "sum_test": test._pnl.sum(),
            "boot_p_neg": p_neg, "boot_ci5": boot_low, "boot_ci95": boot_high,
            "pass_wf": (test._pnl.mean() > 0 and p_neg < 0.10 and train._pnl.mean() > 0),
        })
    return pd.DataFrame(rows)


def main():
    import builtins
    bp = builtins.print
    def fp(*a, **k):
        k.setdefault('flush', True); bp(*a, **k)
    builtins.print = fp

    print("LOADING PANEL...")
    p = load_full_panel()
    print(f"panel rows: {len(p)}, with ret_2m: {p.ret_2m_at_ws.notna().sum()}, with mag_ratio: {p.mag_ratio.notna().sum()}")

    print("\n=== TASK 3 DEEP: sleeves x gates ===")
    t3 = task3_deep(p)
    t3.to_csv(WORK / "task3_deep_sleeve_gate.csv", index=False)
    # Top by sum_pnl with non-NONE gate
    t3_gated = t3[t3.gate != "NONE"]
    print("Top by dpt_lift (n_gate>=200):")
    sub = t3_gated[t3_gated.get("n_gate", 0) >= 200]
    if len(sub) > 0:
        print(sub.sort_values("dpt_lift", ascending=False).head(30).to_string())
    print()
    print("Top by sum_pnl (positive only, n_gate >= 200):")
    pos = t3_gated[(t3_gated.get("n_gate", 0) >= 200) & (t3_gated.dpt_gate > 0)]
    if len(pos) > 0:
        print(pos.sort_values("sum_pnl", ascending=False).head(20).to_string())

    # Baselines for context
    print("\n--- Sleeve baselines (no gate) ---")
    base = t3[t3.gate == "NONE"]
    print(base.sort_values("dpt_base", ascending=False).head(20).to_string())

    print("\n=== TASK 5 DEEP: walk-forward on top combos ===")
    # Top candidates: gated combos with n_gate >= 200 AND dpt_gate > 0
    cands = t3_gated[(t3_gated.get("n_gate", 0) >= 200) & (t3_gated.dpt_gate > -0.1)]
    cands = cands.sort_values("sum_pnl", ascending=False).head(30)
    # Also include baselines for comparison
    base_cands = base[base.dpt_base > 0].sort_values("sum_pnl", ascending=False).head(10)
    base_cands = base_cands.assign(gate="NONE", dpt_gate=base_cands.dpt_base, dpt_lift=0.0)
    all_cands = pd.concat([cands, base_cands], ignore_index=True)
    t5 = task5_walkforward(p, all_cands)
    t5.to_csv(WORK / "task5_walkforward_deep.csv", index=False)
    print("Walk-forward results:")
    print(t5.sort_values(["pass_wf","dpt_test"], ascending=[False, False]).head(30).to_string())
    print()
    print(f"PASSED walk-forward: {t5.pass_wf.sum()} / {len(t5)}")


if __name__ == "__main__":
    main()
